services:
    app:
        build:
            context: .
        container_name: ${DOCKER_CONTAINER_NAME}
        working_dir: /var/www/html
        ports:
            - "8001:80"
        volumes:
            - .:/var/www/html
            - .env:/var/www/html/.env
        environment:
            APP_ENV: local
            DB_HOST: mysql
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: ${DOCKER_CONTAINER_NAME}-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - mysql_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password

volumes:
    mysql_data:
